<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WakeUp\WakeUp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(WAKE_UP_RIMWORLD_MANAGED_DIR)\UnityEngine.CoreModule.dll</HintPath><Private>true</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(WAKE_UP_RIMWORLD_MANAGED_DIR)\UnityEngine.ImageConversionModule.dll</HintPath><Private>true</Private></Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(WAKE_UP_RIMWORLD_MANAGED_DIR)\Assembly-CSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(WAKE_UP_PREPATCHER_ASSEMBLIES_DIR)\0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
